function hFig = PencilSketchGUI()
    % PENCILSKETCHGUI 彩色铅笔素描效果图形用户界面
    
    % 创建主窗口
    hFig = figure('Name', '图像彩色铅笔素描效果', ...
                  'NumberTitle', 'off', ...
                  'Position', [100, 100, 1200, 700], ...
                  'MenuBar', 'none', ...
                  'ToolBar', 'none', ...
                  'Resize', 'on', ...
                  'Color', [0.94 0.94 0.94]);
    
    % 存储数据的结构体
    data = struct();
    data.originalImage = [];
    data.sketchImage = [];
    
    % 创建UI控件
    createControls();
    
    % 将数据存储到figure中
    guidata(hFig, data);
    
    %% 嵌套函数：创建控件
    function createControls()
        % 标题
        uicontrol('Style', 'text', ...
                  'String', '图像彩色铅笔素描效果生成器', ...
                  'Position', [300, 650, 600, 40], ...
                  'FontSize', 18, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.94 0.94 0.94]);
        
        % === 左侧面板：原始图像 ===
        uicontrol('Style', 'text', ...
                  'String', '原始图像', ...
                  'Position', [50, 600, 500, 30], ...
                  'FontSize', 14, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.94 0.94 0.94], ...
                  'HorizontalAlignment', 'left');
        
        data.axesOriginal = axes('Parent', hFig, ...
                                 'Units', 'pixels', ...
                                 'Position', [50, 250, 500, 350]);
        axis(data.axesOriginal, 'off');
        text(0.5, 0.5, '请上传图像', ...
             'HorizontalAlignment', 'center', ...
             'FontSize', 14, 'Color', [0.5 0.5 0.5]);
        
        % === 右侧面板：素描效果 ===
        uicontrol('Style', 'text', ...
                  'String', '素描效果', ...
                  'Position', [650, 600, 500, 30], ...
                  'FontSize', 14, ...
                  'FontWeight', 'bold', ...
                  'BackgroundColor', [0.94 0.94 0.94], ...
                  'HorizontalAlignment', 'left');
        
        data.axesSketch = axes('Parent', hFig, ...
                               'Units', 'pixels', ...
                               'Position', [650, 250, 500, 350]);
        axis(data.axesSketch, 'off');
        text(0.5, 0.5, '等待处理', ...
             'HorizontalAlignment', 'center', ...
             'FontSize', 14, 'Color', [0.5 0.5 0.5]);
        
        % === 控制面板 ===
        panelY = 30;
        
        % 线条阈值控制
        uicontrol('Style', 'text', ...
                  'String', '线条阈值:', ...
                  'Position', [50, panelY + 150, 120, 25], ...
                  'FontSize', 11, ...
                  'BackgroundColor', [0.94 0.94 0.94], ...
                  'HorizontalAlignment', 'left');
        
        data.sliderLine = uicontrol('Style', 'slider', ...
                                    'Min', 0, 'Max', 255, 'Value', 200, ...
                                    'Position', [180, panelY + 150, 300, 25], ...
                                    'Callback', @onSliderChange);
        
        data.textLine = uicontrol('Style', 'text', ...
                                  'String', '200', ...
                                  'Position', [490, panelY + 150, 60, 25], ...
                                  'FontSize', 11, ...
                                  'BackgroundColor', [1 1 1]);
        
        % 颜色饱和度控制
        uicontrol('Style', 'text', ...
                  'String', '颜色饱和度:', ...
                  'Position', [50, panelY + 110, 120, 25], ...
                  'FontSize', 11, ...
                  'BackgroundColor', [0.94 0.94 0.94], ...
                  'HorizontalAlignment', 'left');
        
        data.sliderSaturation = uicontrol('Style', 'slider', ...
                                          'Min', 0.0, 'Max', 2.0, 'Value', 1.0, ...
                                          'Position', [180, panelY + 110, 300, 25], ...
                                          'Callback', @onSliderChange);
        
        data.textSaturation = uicontrol('Style', 'text', ...
                                        'String', '1.00', ...
                                        'Position', [490, panelY + 110, 60, 25], ...
                                        'FontSize', 11, ...
                                        'BackgroundColor', [1 1 1]);
        
        % 明度调整控制
        uicontrol('Style', 'text', ...
                  'String', '明度调整:', ...
                  'Position', [50, panelY + 70, 120, 25], ...
                  'FontSize', 11, ...
                  'BackgroundColor', [0.94 0.94 0.94], ...
                  'HorizontalAlignment', 'left');
        
        data.sliderBrightness = uicontrol('Style', 'slider', ...
                                          'Min', 0, 'Max', 1, 'Value', 0.5, ...
                                          'Position', [180, panelY + 70, 300, 25], ...
                                          'Callback', @onSliderChange);
        
        data.textBrightness = uicontrol('Style', 'text', ...
                                        'String', '0.50', ...
                                        'Position', [490, panelY + 70, 60, 25], ...
                                        'FontSize', 11, ...
                                        'BackgroundColor', [1 1 1]);
        
        % 按钮面板
        uicontrol('Style', 'pushbutton', ...
                  'String', '上传图像', ...
                  'Position', [650, panelY + 150, 150, 40], ...
                  'FontSize', 12, ...
                  'Callback', @onUploadImage);
        
        uicontrol('Style', 'pushbutton', ...
                  'String', '应用效果', ...
                  'Position', [820, panelY + 150, 150, 40], ...
                  'FontSize', 12, ...
                  'Callback', @onApplyEffect);
        
        uicontrol('Style', 'pushbutton', ...
                  'String', '保存图像', ...
                  'Position', [990, panelY + 150, 150, 40], ...
                  'FontSize', 12, ...
                  'Callback', @onSaveImage);
        
        uicontrol('Style', 'pushbutton', ...
                  'String', '重置参数', ...
                  'Position', [650, panelY + 100, 150, 40], ...
                  'FontSize', 12, ...
                  'Callback', @onResetParameters);
        
        % 状态栏
        data.statusText = uicontrol('Style', 'text', ...
                                    'String', '就绪', ...
                                    'Position', [50, panelY + 20, 1100, 30], ...
                                    'FontSize', 10, ...
                                    'BackgroundColor', [0.9 0.95 1], ...
                                    'HorizontalAlignment', 'left', ...
                                    'ForegroundColor', [0 0.4 0.8]);
    end
    
    %% 回调函数：上传图像
    function onUploadImage(~, ~)
        [file, path] = uigetfile({'*.jpg;*.jpeg;*.png;*.bmp', '图像文件 (*.jpg, *.png, *.bmp)'}, '选择图像');
        if isequal(file, 0)
            return;
        end
        
        try
            data = guidata(hFig);
            fullPath = fullfile(path, file);
            data.originalImage = loadImage(fullPath);
            
            % 显示原始图像
            axes(data.axesOriginal);
            imshow(data.originalImage);
            
            % 自动应用默认效果
            data.sketchImage = [];
            set(data.statusText, 'String', sprintf('已加载图像: %s', file));
            
            guidata(hFig, data);
            
            % 自动应用效果
            onApplyEffect([], []);
            
        catch ME
            errordlg(sprintf('加载图像失败: %s', ME.message), '错误');
        end
    end
    
    %% 回调函数：应用效果
    function onApplyEffect(~, ~)
        data = guidata(hFig);
        
        if isempty(data.originalImage)
            warndlg('请先上传图像！', '警告');
            return;
        end
        
        try
            set(data.statusText, 'String', '正在处理，请稍候...');
            drawnow;
            
            % 获取参数
            lineThreshold = get(data.sliderLine, 'Value');
            saturation = get(data.sliderSaturation, 'Value');
            brightness = get(data.sliderBrightness, 'Value');
            
            % 应用铅笔素描效果
            tic;
            data.sketchImage = applyPencilSketch(data.originalImage, ...
                                                 lineThreshold, saturation, brightness);
            processTime = toc;
            
            % 显示结果
            axes(data.axesSketch);
            imshow(data.sketchImage);
            
            set(data.statusText, 'String', ...
                sprintf('处理完成 (耗时: %.2f秒) | 线条: %.0f | 饱和度: %.2f | 明度: %.2f', ...
                        processTime, lineThreshold, saturation, brightness));
            
            guidata(hFig, data);
            
        catch ME
            errordlg(sprintf('处理失败: %s', ME.message), '错误');
            set(data.statusText, 'String', '处理失败');
        end
    end
    
    %% 回调函数：保存图像
    function onSaveImage(~, ~)
        data = guidata(hFig);
        
        if isempty(data.sketchImage)
            warndlg('请先应用效果！', '警告');
            return;
        end
        
        [file, path] = uiputfile({'*.jpg', 'JPEG图像 (*.jpg)'; ...
                                   '*.png', 'PNG图像 (*.png)'}, ...
                                  '保存图像', 'sketch_output.jpg');
        if isequal(file, 0)
            return;
        end
        
        try
            fullPath = fullfile(path, file);
            saveImage(data.sketchImage, fullPath);
            set(data.statusText, 'String', sprintf('图像已保存: %s', file));
            msgbox('图像保存成功！', '成功');
        catch ME
            errordlg(sprintf('保存失败: %s', ME.message), '错误');
        end
    end
    
    %% 回调函数：滑块变化
    function onSliderChange(hObject, ~)
        data = guidata(hFig);
        
        value = get(hObject, 'Value');
        
        if hObject == data.sliderLine
            set(data.textLine, 'String', sprintf('%.0f', value));
        elseif hObject == data.sliderSaturation
            set(data.textSaturation, 'String', sprintf('%.2f', value));
        elseif hObject == data.sliderBrightness
            set(data.textBrightness, 'String', sprintf('%.2f', value));
        end
        
        % 如果已有图像，实时更新（可选，可能较慢）
        % 注释掉下面这行可以禁用实时预览，需要手动点击"应用效果"
        onApplyEffect([], []);
    end
    
    %% 回调函数：重置参数
    function onResetParameters(~, ~)
        data = guidata(hFig);
        
        set(data.sliderLine, 'Value', 200);
        set(data.textLine, 'String', '200');
        
        set(data.sliderSaturation, 'Value', 1.0);
        set(data.textSaturation, 'String', '1.00');
        
        set(data.sliderBrightness, 'Value', 0.5);
        set(data.textBrightness, 'String', '0.50');
        
        set(data.statusText, 'String', '参数已重置为默认值');
        
        % 如果有图像，重新应用效果
        if ~isempty(data.originalImage)
            onApplyEffect([], []);
        end
    end
end